### ISSUE TITLE
Should we support TON DNS?

### ISSUE THREAD

**Issue by skyline9981** [Ton-Dynasty/pytoncenter#17]
# Description:

Currently, our tool does **not support using TON DNS** for address resolution. This limitation restricts our ability to integrate more seamlessly with the TON (The Open Network) ecosystem, potentially impacting our service's usability and accessibility for users and developers within this space.

<img width="1010" alt="image" src="https://github.com/Ton-Dynasty/pytoncenter/assets/75206980/fdc0f9a9-3ade-41fe-a839-345f92c2de6e">

# Issue:

The main issue at hand is the lack of support for TON DNS in our current tool implementation. This means that users are required to use user-friendly addresses for accessing services, which can be a barrier to entry for those less familiar with blockchain technologies or those who prefer the convenience of readable names.

**Comment by alan890104** [comment]
Solved it in #19. Only support for wallet DNS record and only works in mainnet.
